add_newline = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✖](bold red)"

[aws]
disabled = true

[directory]
style = "blue bold"
truncate_to_repo = false

[git_branch]
style = "yellow bold"
format = "[$branch]($style) "

[git_commit]
style = "yellow"
format = "- [$hash]($style) "

[git_status]
style = "bold"
format = "\\(([$all_status$ahead_behind]($style))\\) "
stashed = ""
ahead = "[⇡${count}](bold green)"
behind = "[⇣${count}](bold red)"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

[line_break]
disabled = true

[nodejs]
format = "[$symbol($version )]($style)"

[package]
disabled = true

# [custom]
#
# add notifier to show whether I'm in bash or zsh
# example tests:
# if [ ! -z $BASH_VERSION ] ; then echo 'BASH' ; fi
# if [ ! -z $ZSH_VERSION ] ; then echo 'ZSH' ; fi
